//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShip.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleShip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream BeepSound1 {
            get {
                return ResourceManager.GetStream("BeepSound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream EndCallSound {
            get {
                return ResourceManager.GetStream("EndCallSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream OpponentCallsSound {
            get {
                return ResourceManager.GetStream("OpponentCallsSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stun.a-mm.tv:3478
        ///stun.rounds.com:3478
        ///stun.sipnet.net:3478
        ///stun.voip.blackberry.com:3478
        ///stun.sipnet.ru:3478
        ///stun.petcube.com:3478
        ///stun.twt.it:3478
        ///stun.srce.hr:3478
        ///stun.sysadminman.net:3478
        ///stun.telbo.com:3478
        ///stun.telefacil.com:3478
        ///stun.tng.de:3478
        ///stun.ucw.cz:3478
        ///stun.u-blox.com:3478
        ///stun.ucallweconn.net:3478
        ///stun.solnet.ch:3478
        ///stun.vivox.com:3478
        ///stun.vline.com:3478
        ///stun.vo.lu:3478
        ///stun.sonetel.com:3478
        ///stun.smsdiscount.com:3478
        ///stun.solcon.nl:3478
        ///stun.snafu.de:3478
        ///stun.voi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StunServers {
            get {
                return ResourceManager.GetString("StunServers", resourceCulture);
            }
        }
    }
}
