//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShip.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleShip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stun.a-mm.tv:3478
        ///stun.jappix.com:3478
        ///stun.rounds.com:3478
        ///stun.sipnet.net:3478
        ///numb.viagenie.ca:3478
        ///stun.12connect.com:3478
        ///stun.12voip.com:3478
        ///stun.1und1.de:3478
        ///stun.2talk.co.nz:3478
        ///stun.2talk.com:3478
        ///stun.3clogic.com:3478
        ///stun.advfn.com:3478
        ///stun.aeta.com:3478
        ///stun.aeta-audio.com:3478
        ///stun.awt.be:3478
        ///stun.b2b2c.ca:3478
        ///stun.bluesip.net:3478
        ///stun.budgetphone.nl:3478
        ///stun.cablenet-as.net:3478
        ///stun.callwithus.com:3478
        ///stun.cheapvoip.com:3478
        ///stun.cloopen.com:3478
        ///stun.comfi.com: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StunServers {
            get {
                return ResourceManager.GetString("StunServers", resourceCulture);
            }
        }
    }
}
